'use client';
import {FormEvent,useEffect,useState} from 'react';
import './creator.css';

type Role='founder'|'admin'|'secretary'|'staff'|'member';
type Report={id:number;reason:string;details:string;status:string;createdAt:number;message:string;reportedName:string;reportedUsername:string;reportedUserId:number;reporterName:string};
type Person={id:number;username:string;name:string;avatarKey:string|null;role:Role;accountStatus:'active'|'paused'|'suspended'|'banned';suspendedUntil:number|null;warningsCount:number;createdAt:number};
type Me={id:number;role:Role};

const labels:Record<Role,string>={founder:'Founder/Admin',admin:'Admin',secretary:'Admin Secretary',staff:'Staff/Orderly',member:'Member'};
const rank:Record<Role,number>={member:0,staff:1,secretary:2,admin:3,founder:4};

export default function Creator(){
 const [reports,setReports]=useState<Report[]>([]),[people,setPeople]=useState<Person[]>([]),[me,setMe]=useState<Me|null>(null),[state,setState]=useState('Loading dashboard…'),[needsLogin,setNeedsLogin]=useState(false),[loginError,setLoginError]=useState(''),[tab,setTab]=useState<'people'|'reports'>('people'),[notice,setNotice]=useState('');
 async function load(){
  try{
   const [rr,mr]=await Promise.all([fetch('/api/reports',{cache:'no-store'}),fetch('/api/moderation',{cache:'no-store'})]);
   if(rr.status===403||mr.status===403||rr.status===401||mr.status===401){setNeedsLogin(true);setState('');return}
   const [rd,md]=await Promise.all([rr.json(),mr.json()]) as [any,any];
   if(!rr.ok||!mr.ok){setState(rd.error??md.error??'Could not open the dashboard.');return}
   setReports(rd.reports??[]);setPeople(md.users??[]);setMe(md.me??null);setState('');setNeedsLogin(false);
  }catch{setState('Could not refresh the dashboard.')}
 }
 useEffect(()=>{load();const id=setInterval(()=>{if(!needsLogin)load()},2500);return()=>clearInterval(id)},[needsLogin]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoginError('');const f=new FormData(e.currentTarget),r=await fetch('/api/creator-auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:f.get('username'),password:f.get('password')})}),d=await r.json() as any;if(!r.ok)return setLoginError(d.error??'Sign in did not work.');await load()}
 async function updateReport(id:number){const r=await fetch('/api/reports',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:'reviewed'})}),d=await r.json() as any;if(!r.ok)setNotice(d.error??'Could not update the report.');else{setNotice('Report marked reviewed.');await load()}}
 async function moderate(userId:number,action:string,extra:Record<string,unknown>={}){setNotice('');const r=await fetch('/api/moderation',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,action,...extra})}),d=await r.json() as any;setNotice(d.message??d.error??(r.ok?'Account updated.':'That action did not work.'));if(r.ok)await load();return r.ok}
 function canManage(p:Person){return !!me&&p.id!==me.id&&rank[me.role]>rank[p.role]}
 function warn(p:Person){const reason=prompt(`What warning should ${p.name} receive?`);if(reason?.trim())moderate(p.id,'warn',{reason})}
 function suspend(p:Person){if(!me)return;const max=me.role==='staff'?3:me.role==='secretary'?7:365,answer=prompt(`Suspend ${p.name} for how many days? (1–${max})`);if(!answer)return;const days=Number(answer);if(!Number.isInteger(days)||days<1||days>max){setNotice(`Choose a whole number from 1 to ${max}.`);return}const reason=prompt('Reason for the suspension (optional):')??'';moderate(p.id,'suspend',{days,reason})}
 function accountAction(p:Person,action:'pause'|'ban'|'restore'){const words={pause:'pause',ban:'permanently ban',restore:'restore'};if(confirm(`${words[action]} ${p.name}'s account?`))moderate(p.id,action)}
 if(needsLogin)return <main className="creator-login"><section><i>🐈</i><p>STAFF CENTER</p><h1>Creator sign in</h1><span>Use the founder Cat Chat account. Staff who are already signed in can open this page from the chat.</span><form onSubmit={login}><label>Username<input name="username" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{loginError&&<strong>{loginError}</strong>}<button>Open dashboard</button></form><a href="/">← Back to The Cat Chat</a></section></main>;
 return <main className="creator"><header><a href="/">🐈 <b>The Cat Chat</b></a><div><RoleBadge role={me?.role??'member'}/><a className="chat-link" href="/">Open chat →</a></div></header><section className="hero"><div><p>SAFETY DASHBOARD</p><h1>Keep Cat Chat kind.</h1><span>See every account, choose staff roles, respond to reports, and help everyone behave.</span></div><aside><b>{reports.filter(r=>r.status==='new').length}</b><small>new reports</small></aside></section><nav className="dashboard-tabs"><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}>People <span>{people.length}</span></button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Reports <span>{reports.filter(r=>r.status==='new').length}</span></button></nav>{notice&&<div className="dashboard-notice" onClick={()=>setNotice('')}>{notice}<button aria-label="Dismiss">×</button></div>}{state&&<div className="notice">{state}</div>}{tab==='people'?<People people={people} me={me} canManage={canManage} moderate={moderate} warn={warn} suspend={suspend} accountAction={accountAction}/>:<Reports reports={reports} updateReport={updateReport} openPerson={()=>setTab('people')}/>}</main>;
}

function People({people,me,canManage,moderate,warn,suspend,accountAction}:{people:Person[];me:Me|null;canManage:(p:Person)=>boolean;moderate:(id:number,action:string,extra?:Record<string,unknown>)=>Promise<boolean>;warn:(p:Person)=>void;suspend:(p:Person)=>void;accountAction:(p:Person,a:'pause'|'ban'|'restore')=>void}){
 return <section className="people-section"><div className="section-title"><div><h2>Everyone in Cat Chat</h2><p>Every active account appears here. New accounts are added at the bottom; permanent bans disappear.</p></div><span>{people.length} accounts</span></div><div className="permission-guide"><b>Staff powers</b><span><RoleBadge role="admin"/> delete messages · warn · pause · suspend · ban</span><span><RoleBadge role="secretary"/> delete messages · warn · pause · suspend up to 7 days</span><span><RoleBadge role="staff"/> delete messages · warn · suspend up to 3 days</span></div><div className="people-grid">{people.map(p=>{const manageable=canManage(p),isSelf=p.id===me?.id,canRestore=manageable&&(p.accountStatus==='suspended'||(rank[me?.role??'member']>=2&&p.accountStatus==='paused'));return <article className={`person-card status-${p.accountStatus}`} key={p.id}><div className="person-head"><Avatar person={p}/><div><div className="person-name"><h3>{p.name}</h3><RoleBadge role={p.role}/>{isSelf&&<em>YOU</em>}</div><p>@{p.username}</p></div><Status person={p}/></div><div className="person-facts"><span><b>{p.warningsCount}</b> warnings</span><span>Joined {new Date(p.createdAt).toLocaleDateString()}</span></div>{me?.role==='founder'&&p.role!=='founder'&&<div className="role-control"><label>Staff role<select defaultValue={p.role} id={`role-${p.id}`}><option value="member">Member</option><option value="admin">Admin</option><option value="secretary">Admin Secretary</option><option value="staff">Staff/Orderly</option></select></label><button onClick={()=>{const el=document.querySelector<HTMLSelectElement>(`#role-${p.id}`);if(el)moderate(p.id,'role',{role:el.value})}}>Save role</button></div>}{manageable&&<div className="person-actions"><button onClick={()=>warn(p)}>⚠ Warn</button><button onClick={()=>suspend(p)}>⏳ Suspend</button>{rank[me!.role]>=2&&<button onClick={()=>accountAction(p,'pause')}>Ⅱ Pause</button>}{canRestore&&<button className="restore" onClick={()=>accountAction(p,'restore')}>✓ Unpause / unsuspend</button>}{rank[me!.role]>=3&&<button className="danger" onClick={()=>accountAction(p,'ban')}>Permanent ban</button>}</div>}{!manageable&&p.role!=='founder'&&!isSelf&&<p className="protected-note">This account is at or above your staff level.</p>}</article>})}</div></section>;
}

function Reports({reports,updateReport,openPerson}:{reports:Report[];updateReport:(id:number)=>void;openPerson:()=>void}){return <section className="reports"><div className="section-title"><div><h2>Reports</h2><p>New reports appear automatically.</p></div><span>{reports.length} total</span></div>{!reports.length&&<div className="empty-reports">🐾<h3>Everything looks good</h3><p>No one has sent a report yet.</p></div>}{reports.map(r=><article key={r.id} className={r.status==='new'?'new':''}><div className="report-top"><span className="badge">{r.status==='new'?'NEW':'REVIEWED'}</span><time>{new Date(r.createdAt).toLocaleString()}</time></div><h3>{r.reason}</h3><blockquote>“{r.message}”</blockquote>{r.details&&<p className="details"><b>What happened:</b> {r.details}</p>}<dl><div><dt>Reported person</dt><dd>{r.reportedName} <small>@{r.reportedUsername}</small></dd></div><div><dt>Reported by</dt><dd>{r.reporterName}</dd></div></dl><div className="actions">{r.status==='new'&&<button onClick={()=>updateReport(r.id)}>✓ Mark reviewed</button>}<button className="manage" onClick={openPerson}>Manage accounts</button></div></article>)}</section>}

function Avatar({person}:{person:Person}){const src=person.avatarKey?`/api/avatar/${person.avatarKey.replace('avatars/','')}`:'';return <i className="person-avatar" style={src?{backgroundImage:`url(${src})`}:undefined}>{src?'':person.name.slice(0,1).toUpperCase()}</i>}
function RoleBadge({role}:{role:Role}){if(role==='member')return null;return <b className={`role-badge role-${role}`}>{labels[role]}</b>}
function Status({person}:{person:Person}){let text:string=person.accountStatus;if(person.accountStatus==='suspended'&&person.suspendedUntil)text=`Suspended until ${new Date(person.suspendedUntil).toLocaleDateString()}`;return <span className={`account-status ${person.accountStatus}`}>{text}</span>}
