'use client';import {FormEvent,useEffect,useRef,useState} from 'react';
type User={id:number;username:string;name:string;avatarKey:string|null;role:string};type Msg={id:number;body:string;createdAt:number;userId:number;name:string;avatarKey:string|null};type Chat={id:number;name:string;type:string};type Person={id:number;username:string;name:string;avatarKey:string|null};const MAIN={id:1,name:'Main School Chat',type:'main'};
export default function Home(){const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[join,setJoin]=useState(true),[error,setError]=useState(''),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[profile,setProfile]=useState(false),[report,setReport]=useState(false),[menu,setMenu]=useState(false),[create,setCreate]=useState(false),[chats,setChats]=useState<Chat[]>([MAIN]),[people,setPeople]=useState<Person[]>([]),[active,setActive]=useState(1);const last=useRef(0),end=useRef<HTMLDivElement>(null),chat=chats.find(c=>c.id===active)??MAIN;
useEffect(()=>{fetch('/api/auth').then(r=>r.json()).then(d=>setUser(d.user??null)).finally(()=>setReady(true))},[]);
useEffect(()=>{if(!user)return;const load=()=>fetch('/api/home',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.chats)setChats(d.chats);if(d.people)setPeople(d.people)}).catch(()=>{});load();const id=setInterval(load,7000);return()=>clearInterval(id)},[user]);
useEffect(()=>{if(!user)return;let on=true;setMessages([]);last.current=0;const load=()=>fetch(`/api/messages?conversationId=${active}&since=${last.current}`,{cache:'no-store'}).then(r=>r.json()).then(d=>{if(on&&Array.isArray(d.messages)&&d.messages.length){setMessages(v=>[...v,...d.messages]);last.current=d.messages[d.messages.length-1].id}}).catch(()=>{});load();const id=setInterval(load,1500);return()=>{on=false;clearInterval(id)}},[user,active]);
async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget),r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:join?'register':'login',name:f.get('name'),username:f.get('username'),password:f.get('password')})}),d=await r.json();if(r.ok)setUser(d.user);else setError(d.error)}
async function send(e:FormEvent){e.preventDefault();const body=text.trim();if(!body)return;setText('');setError('');try{const r=await fetch('/api/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body,conversationId:active})}),d=await r.json();if(!r.ok){setText(body);setError(d.error??'Message could not send. Try again.')}}catch{setText(body);setError('Message could not send. Try again.')}}
async function makeChat(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch('/api/chats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:f.get('type'),name:f.get('name'),memberIds:f.getAll('members').map(Number)})}),d=await r.json();if(r.ok){setChats(v=>[...v,d.chat]);setActive(d.chat.id);setCreate(false)}else setError(d.error)}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:f.get('name')})}),d=await r.json();if(r.ok){setUser(d.user);setProfile(false)}}
async function photo(file:File){const f=new FormData();f.append('photo',file);const r=await fetch('/api/profile/photo',{method:'POST',body:f}),d=await r.json();if(r.ok&&user)setUser({...user,avatarKey:d.avatarKey})}async function logout(){await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'logout'})});setUser(null);setProfile(false)}
async function flag(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await fetch('/api/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messageId:Number(f.get('message')),reason:f.get('reason')})});setReport(false)}
if(!ready)return <main className="loading"><i>🐈</i><h1>The Cat Chat</h1><p>Opening…</p></main>;
if(!user)return <main className="welcome"><section><i>🐈</i><b>THE CAT CHAT</b><h1>{join?'Create your account':'Welcome back'}</h1><p>Use a Cat Chat account. No ChatGPT sign-in needed.</p><form onSubmit={auth}>{join&&<label>Display name<input name="name" required maxLength={30}/></label>}<label>Username<input name="username" required/></label><label>Password<input name="password" type="password" minLength={8} required/></label>{error&&<strong>{error}</strong>}<button>{join?'Create account':'Sign in'}</button></form><button className="swap" onClick={()=>{setJoin(!join);setError('')}}>{join?'Already have an account?':'Create a new account'}</button></section></main>;
return <main className="app"><header><button className="menu" onClick={()=>setMenu(!menu)}>☰</button><div><i>🐈</i><span><b>The Cat Chat</b><small>{chat.name}</small></span></div><button onClick={()=>setProfile(true)}><Avatar u={user}/></button></header>{menu&&<aside className="chatmenu"><h2>Chats</h2>{chats.map(c=><button key={c.id} onClick={()=>{setActive(c.id);setMenu(false)}} className={active===c.id?'active':''}>{c.type==='private'?'♡':'#'} {c.name}</button>)}<button className="add" onClick={()=>{setMenu(false);setCreate(true)}}>＋ Create chat</button></aside>}<div className="room"><b>{chat.name}</b><span>{chat.type==='main'?'Everyone begins here':chat.type==='private'?'Private chat':'Group chat'}</span></div><section className="feed">{messages.length===0?<div className="empty"><i>🐾</i><h2>No messages yet</h2><p>Be the first person to say hello.</p></div>:messages.map(m=><article className={m.userId===user.id?'mine':''} key={m.id}><Avatar u={m}/><div><span>{m.userId===user.id?'You':m.name} · {new Date(m.createdAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span><p>{m.body}</p></div></article>)}<div ref={end}/></section><form className="send" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…" maxLength={500}/><button>Send</button></form><footer><button onClick={()=>setReport(true)}>⚑ Report to the creator</button><span>Kind words only</span></footer>
{create&&<Modal close={()=>setCreate(false)}><h2>Create a chat</h2><form onSubmit={makeChat}><label>Type<select name="type"><option value="group">Group chat</option><option value="private">Private chat</option></select></label><label>Group name<input name="name"/></label><fieldset><legend>Choose people</legend>{people.map(p=><label className="person" key={p.id}><input type="checkbox" name="members" value={p.id}/><Avatar u={p}/>{p.name}</label>)}</fieldset>{error&&<strong>{error}</strong>}<button>Create chat</button></form></Modal>}
{profile&&<Modal close={()=>setProfile(false)}><Avatar u={user}/><label className="upload">Change profile picture<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&photo(e.target.files[0])}/></label><h2>Your profile</h2><form onSubmit={save}><label>Display name<input name="name" defaultValue={user.name}/></label><button>Save</button></form><button className="logout" onClick={logout}>Sign out</button></Modal>}
{report&&<Modal close={()=>setReport(false)}><h2>Report a message</h2><p>This goes privately to the creator.</p><form onSubmit={flag}><label>Message<select name="message" required><option value="">Choose one</option>{messages.filter(m=>m.userId!==user.id).map(m=><option value={m.id} key={m.id}>{m.name}: {m.body.slice(0,50)}</option>)}</select></label><label>Reason<select name="reason"><option>Bullying or unkind behavior</option><option>Unsafe message</option><option>Private information</option><option>Spam</option></select></label><button>Send report</button></form></Modal>}</main>}
function Avatar({u}:{u:{name:string;avatarKey?:string|null}}){const src=u.avatarKey?`/api/avatar/${u.avatarKey.replace('avatars/','')}`:'';return <i className="avatar" style={src?{backgroundImage:`url(${src})`}:undefined}>{src?'':u.name.slice(0,1).toUpperCase()}</i>}function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="shade" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button>{children}</section></div>}
